service: nodejs-assignment

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    APP_NAME: ${self:service}
    AWS_ACCESS_KEY_ID: id_key
    AWS_SECRET_ACCESS_KEY: access_key

package:
  exclude:
    - .env
    - coverage/**

plugins:
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

functions:
# get all loans
  getLoans:
    name: getLoans
    handler: src/app1/loanHandler.getLoans
    events:
      - http:
          path: /get
          method: get
# get loan by id
  getLoan:
    name: getLoan
    handler: src/app1/loanHandler.getLoan
    events:
      - http:
          path: /get/{id}
          method: get
# create new loan
  createLoan:
    name: createLoan
    handler: src/app1/loanHandler.createLoan
    events:
      - http:
          path: /create
          method: post
          
# update loan
  updateLoan:
    name: updateLoan
    handler: src/app1/loanHandler.updateLoan
    events:
      - http:
          path: /update/{id}
          method: put

# disburse loan
  disburseLoan:
    name: disburseLoan
    handler: src/app2/disburseHandler.disburseLoan
    events:
      - http:
          path: /disburse/{id}
          method: put